---
- name: Configure Apache on all servers in 'web' group
  hosts: web
  become: yes
  tasks:
    - name: Install Apache on Debian-based distros
      apt:
        name: apache2
        state: present
    - name: Start Apache service
      service:
        name: apache2
        state: started
        enabled: yes